### PR TITLE
upgrade to pyqt6

### PR DESCRIPTION
**Pull request by BishopWolf**
videomorph working on Manjaro using pyqt6 and Qt6.4.1

### CODE REVIEW

**Comment by BishopWolf** [comment]
Test failed with error
```
ERROR: Could not find a version that satisfies the requirement PyQt6==6.4.1 (from versions: 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.4.0)
```
6.4.0 should theoretically work too, but I haven't tested

**Comment by BishopWolf** [comment]
The error is now 
```
ValueError: Command ffmpeg not found
```
This is not anymore on my control

**Comment by leonel-lordford** [comment]
@BishopWolf thanks for this wonderful PR!!! I am sure the whole team will be extremely happy about it. We will review it and give you feedback!!!

**Comment by BishopWolf** [comment]
Error is now 
```
ERROR: Failure: TypeError (__init__() missing 1 required positional argument: 'path')
```
This happens in the tests while instantiating the Library class, but it requires a path in its constructor: see test_converter.py:L33 and library.py:L32

**Comment by BishopWolf** [comment]
Videomorph is running fine
imagen

**Comment by lpozo** [comment]
This looks good to me. My only concern is that we're doing PRs against `master` instead of `develop`.

**Comment by BishopWolf** [comment]
> This looks good to me. My only concern is that we're doing PRs against `master` instead of `develop`.

Thanks for the catch up! I didn't realize that! Sorry, I will rebranch the PR

**Comment by BishopWolf** [comment]
Created new PR to develop
